export const GET_COUNTRIES = 'GET_COUNTRIES';
export const GET_COUNTRY = 'GET_COUNTRY';

export const SORT_COUNTRIES = 'SORT_COUNTRIES';
export const FILTER_COUNTRIES = 'FILTER_COUNTRIES';

export const GET_ACTIVITIES = 'GET_ACTIVITIES';
export const GET_ACTIVITY = 'GET_ACTIVITY';
export const CREATE_ACTIVITY = 'CREATE_ACTIVITY';
export const DISABLE_ACTIVITY = 'DISABLE_ACTIVITY';
export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const RESTORE_ACTIVITY = 'RESTORE_ACTIVITY';
export const UPDATE_ACTIVITY = 'UPDATE_ACTIVITY';

export const CLEAN_UP = 'CLEAN_UP';